### PR TITLE
Allow setting led text indefinitely

### PR DESCRIPTION
**Pull request by soraxas**
Currently set led text is always blocking (and resets afterward).

This PR enables setting led set indefinitely if given t <= 0

### CODE REVIEW

**Comment by kareltucek** [comment]
Good idea, and a good job! Just a few technical details:

1. Please, sign the CLA in the official repository according to https://github.com/UltimateHackingKeyboard/firmware/blob/master/CONTRIBUTING.md . This enures that your code can be propagated back into the stock in the future.

2. Please, rebase the PR onto `kareltucek:common_trunk_upstream`, and post against `kareltucek:common_trunk_upstream`.

3. Generally, please use the kareltucek:common_trunk_upstream for development. It contains the most up-to-date code, and is likely to also be headed into stock firmware in the future (unlike master, which contains fork-only stuff).   (You will need to compile using either `make CUSTOM_CFLAGS=-DEXTENDED_MACROS` / `./make-release.js --extendedMacros`.)

**Comment by soraxas** [comment]
Thanks for the reply and the instructions, I will do that. Should the CLA be made against this repo or the official repo?

**Comment by kareltucek** [comment]
Preferably official. (Although in the end it should not matter much.)

/edit: definitely official - it matters in case Laszlo squashes things on merges, which he often does.

**Comment by soraxas** [comment]
Hi! I was a bit confused by the new `command` type of `macroAction.macroActionType` as it does not exists in agent. I realised that the current sub-repository of agent in the `kareltucek:common_trunk_upstream` branch is still pointing to the older `agent` commit before https://github.com/UltimateHackingKeyboard/agent/pull/1545. Might want to update that?

**Comment by kareltucek** [comment]
>  realised that the current sub-repository of agent in the kareltucek:common_trunk_upstream branch is still pointing 

I have merged uhk/master today, so I assume that correct reference should be present now.

**Pull request merged**
