### PR TITLE
Update MACRO_DOCS.md

### PR DESCRIPTION
**Pull request by rafaelpirolla**

### CODE REVIEW

**Comment by kareltucek** [comment]
I should not accept the PR unless/until you have signed the cla. 

(Also, isn't it obvious that in order to call a macro command you first have to create corresponding macro?)

**Comment by kareltucek** [comment]
Actually two more problems:

- this change needs to be done on common_trunk_upstream. 

- it still seems just as ambiguous as before to me, since it is not clear that the macro does not need to be bound to the same key as the one whose keyid is sought.

I will try to clarify as part of `resolveNextKeyId`'s documentation. Making docs of other commands more complex for sake of clarification is not the way to go anyways...

**Comment by kareltucek** [comment]
I hope this makes the usage clear: [https://github.com/kareltucek/firmware/commit/660186595776939a9134b217f3ea356698d3c261](https://github.com/kareltucek/firmware/commit/660186595776939a9134b217f3ea356698d3c261). It will make it to master eventually.

**Comment by rafaelpirolla** [comment]
It took a while to get that I should bind only that function to a key, so I thought to write in the example something that would trigger the idea in my head. Sad to say it was not obvious to me... It is now anyhow.

But hey, just an idea since I had issues to understand it.

**Comment by kareltucek** [comment]
> Sad to say it was not obvious to me... It is now anyhow.

I see. "Author's blindness" is on me, thanks for pointing out!

**Pull request closed without merging**
